# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

require 'support/coverage_loader'

def expect_output(output)
  expect($stdout).to receive(:print).with(output)
end

def input(input)
  if input.is_a?(String)
    expect($stdin).to receive(:gets).once.and_return(input)
  elsif input.is_a?(Array)
    expect($stdin).to receive(:gets).exactly(input.size).times.and_return(*input)
  else
  end
end

require 'input_reader'
